README_ERリンク追加
yasu-da-joe/ycr_app pull request #9
Opened 2024-09-13 08:37 UTC by yasu-da-joe

ER図を提出します。

2024-09-14 02:20 UTC, kashiwagi-rena commented
ご提出いただきありがとうございます。
READMEを見ながら確認したかったのですが、見当たりませんでした。
また、Files changedを確認したところ前の記述が削除されていました。
こちら一旦対応していただきたいです。

また、テーブルについての説明を共有した下さると、スムーズに確認することが可能です。ご対応よろしくお願いいたします。

2024-09-14 09:50 UTC, yasu-da-joe commented
カリキュラム再確認して、追記の記載があるのを見逃しておりました。
改めて、README更新いたしました。また、README内に、テーブル説明文を追加しております。
ご確認お願いいたします。

2024-09-15 08:26 UTC, tarakish requested changes
対応ありがとうございます。
まずは各カラムについてデータ型も記載するように修正をお願いします。

他の講師もレビューを行うため、またER図の変遷がプルリクエストを見れば分かるようにしたいため、お手数ですが最新のER図のスクリーンショットを都度コメント欄に画像が表示される形で掲載をお願いいたします。
画像掲載の際はURLではなく、画像がそのまま表示される形にしてください。（Gyazo・マークダウン）

2024-09-15 12:35 UTC, yasu-da-joe commented
ご確認ありがとうございます。

・データ型追記しました。

・スクショ以下です。
[![Image from Gyazo](https://i.gyazo.com/0ac2cc2c94218e0dffdd7e9ac577352f.png)](https://gyazo.com/0ac2cc2c94218e0dffdd7e9ac577352f)

2024-09-17 02:37 UTC, Tsuchiya2 commented
対応ありがとうございます。
カラム名が「テーブル名_xxx」となっているカラムがありますね。
呼び出し時に@post.post_nameとするより、@post.nameの方が直感的になるため、「テーブル名_xxx」と付いているカラムは命名を修正してください。

2024-09-17 07:02 UTC, yasu-da-joe commented
ご確認ありがとうございます。内容修正いたしました。READMEも合わせて更新しております。ご確認お願いします。

[![Image from Gyazo](https://i.gyazo.com/4545268da234449621d87097b069c1a6.png)](https://gyazo.com/4545268da234449621d87097b069c1a6)

2024-09-19 03:23 UTC, Tsuchiya2 commented
概ね良いかと思います。LGTMです。
修正が必要になった際は適宜修正して開発を進めましょう。

2024-09-20 09:49 UTC, merged